require 'tempfile'

lane :beta do
  # Write .p8 key to temp file
  file = Tempfile.new(['asc', '.p8'])
  file.write(ENV["APPSTORE_API_PRIVATE_KEY"])
  file.close

  api_key = app_store_connect_api_key(
    key_filepath: file.path,
    key_id: ENV["APPSTORE_API_KEY_ID"],
    issuer_id: ENV["APPSTORE_ISSUER_ID"],
    in_house: false
  )

    # Fetch certificates & provisioning profiles from your private repo
    match(
      type: "appstore",                  # App Store distribution
      readonly: true,                   # Set false to allow creating/updating profiles
      git_url: ENV["MATCH_GIT_URL"],     # Private GitHub certs repo
      git_branch: ENV["MATCH_GIT_BRANCH"],   # e.g., "main"
      app_identifier: "com.dimpho.cameraDemo",
      username: ENV["APPSTORE_TEAM_ID"], # Team ID or Apple ID email (Fastlane uses for context)
      api_key: api_key,
      git_basic_authorization: ENV["CERTS_REPO_PAT"]
    )

    # Build the IPA
    build_app(
      scheme: "Runner",
      export_method: "app-store",
      include_bitcode: true,
      clean: true,
      output_directory: "build/ios/ipa"
    )

    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      app_identifier: "com.dimpho.cameraDemo",
      api_key: api_key
    )
  end
end
