name: Build & Upload iOS to TestFlight

on:
  push:
    branches:
      - main

jobs:
  build:
    name: iOS Build & TestFlight
    runs-on: macos-latest

    env:
      MATCH_GIT_URL: https://Dimpho-S:${{ secrets.CERTS_REPO_PAT }}@github.com/Dimpho-S/cameraDemo_certs.git
      MATCH_GIT_BRANCH: ${{ secrets.MATCH_GIT_BRANCH }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      APPSTORE_TEAM_ID: ${{ secrets.APPSTORE_TEAM_ID }}
      APP_STORE_JSON_KEY: ${{ secrets.APP_STORE_JSON_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.3"

      - name: Install dependencies
        run: flutter pub get

      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      - name: Build and upload to TestFlight
        run: |
          cd ios
          fastlane beta
